services:
  app:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "8080:5000"
    environment:
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://joro:12qwaszx@db:5432/elonfan
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - FLASK_APP=app.py
      - POSTGRES_USER=joro
      - POSTGRES_PASSWORD=12qwaszx
      - POSTGRES_DB=elonfan

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: