"""Add transcript field

Revision ID: 0a90d14c6a8f
Revises: 
Create Date: 2024-09-17 18:22:01.303167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a90d14c6a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_column('transcript')

    # ### end Alembic commands ###
